import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";

const ALLOWED_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const MAX_BYTES = 8 * 1024 * 1024; // 8MB

const ALLOWED_VIDEO_TYPES = new Set(["video/mp4", "video/webm", "video/quicktime"]);
const MAX_VIDEO_BYTES = 25 * 1024 * 1024; // 25MB, generous for a 30s clip

const PRIVATE_ROOT = path.join(process.cwd(), "storage", "id-verifications");
const PUBLIC_ROOT = path.join(process.cwd(), "public", "uploads", "coach-photos");
const VIDEO_ROOT = path.join(process.cwd(), "public", "uploads", "coach-videos");

function extFromType(type: string): string {
  if (type === "image/png") return "png";
  if (type === "image/webp") return "webp";
  return "jpg";
}

function extFromVideoType(type: string): string {
  if (type === "video/webm") return "webm";
  if (type === "video/quicktime") return "mov";
  return "mp4";
}

async function readAndValidate(file: File) {
  if (!ALLOWED_TYPES.has(file.type)) {
    throw new Error("Only JPEG, PNG, or WEBP images are allowed.");
  }
  if (file.size > MAX_BYTES) {
    throw new Error("File is too large (8MB max).");
  }
  const buffer = Buffer.from(await file.arrayBuffer());
  return buffer;
}

/**
 * Saves a coach's school ID photo to a private, non-public directory.
 * Returns a path stored on CoachProfile.idPhotoPath and served only via
 * /api/private-files, which enforces owner/admin access.
 */
export async function saveIdPhoto(coachProfileId: string, file: File): Promise<string> {
  const buffer = await readAndValidate(file);
  await mkdir(PRIVATE_ROOT, { recursive: true });
  const filename = `${coachProfileId}-${randomUUID()}.${extFromType(file.type)}`;
  await writeFile(path.join(PRIVATE_ROOT, filename), buffer);
  return filename;
}

export function resolvePrivateFilePath(filename: string): string {
  // filename is generated by us (uuid-based) and never derived from
  // user-controlled path segments, so this is safe from traversal.
  const safe = path.basename(filename);
  return path.join(PRIVATE_ROOT, safe);
}

/**
 * Saves a coach's public profile photo under /public and returns the
 * public URL path to store on CoachProfile.profilePhotoUrl.
 */
export async function savePublicProfilePhoto(coachProfileId: string, file: File): Promise<string> {
  const buffer = await readAndValidate(file);
  await mkdir(PUBLIC_ROOT, { recursive: true });
  const filename = `${coachProfileId}-${randomUUID()}.${extFromType(file.type)}`;
  await writeFile(path.join(PUBLIC_ROOT, filename), buffer);
  return `/uploads/coach-photos/${filename}`;
}

/**
 * Saves a coach's short intro video. Duration is validated client-side
 * (max 30s, enforced before upload); this is a best-effort file-size cap
 * as a server-side backstop since checking real video duration needs a
 * media-processing library we don't have in this stack.
 */
export async function saveIntroVideo(coachProfileId: string, file: File): Promise<string> {
  if (!ALLOWED_VIDEO_TYPES.has(file.type)) {
    throw new Error("Only MP4, WEBM, or MOV videos are allowed.");
  }
  if (file.size > MAX_VIDEO_BYTES) {
    throw new Error("Video is too large (25MB max — keep it under 30 seconds).");
  }
  const buffer = Buffer.from(await file.arrayBuffer());
  await mkdir(VIDEO_ROOT, { recursive: true });
  const filename = `${coachProfileId}-${randomUUID()}.${extFromVideoType(file.type)}`;
  await writeFile(path.join(VIDEO_ROOT, filename), buffer);
  return `/uploads/coach-videos/${filename}`;
}
